### ISSUE TITLE
Relax requirements to allow updating libraries

### ISSUE THREAD

**Issue by bignose-debian** [torfsen/service#1]
The Pip requirements specifiers are all locked to exact versions. This thwarts upgrading one of the dependent libraries (e.g. ‘python-daemon’) to address bugs and new features.

Please re-visit the dependencies, using “or later” dependencies where appropriate for all dependencies.

**Comment by torfsen** [comment]
The actual dependencies in `setup.py` don't carry any version information at all, so they use the installed version or (if the required package is not installed) the latest available.

The requirements in the `requirements-X.Y.txt` files are only used for testing, see `tox.ini`.

**Comment by torfsen** [comment]
BTW, I just re-organized the dependencies while adding tests for Python 3.5. Now even the dev/test requirements are unversioned :wink:
