### ISSUE TITLE
Advance Status Support

### ISSUE THREAD

**Issue by chekolyn** [torfsen/service#4]
Currently it's very hard to get visibility into what the Forked Process is doing.
The only status available is from the service looking at the PID file via the **is_running()** function.

Imagine you need a service that has multiple threads, I want to expose how many threads are running by issuing the status call to main service status. 
Or that I want to expose 1min, 5min, 60min counter values for the service itself. 

Is there currently a way to do this? Am I missing something?

If not, is there a way to make the service listen on a socket for status reporting purposes.
Something like this: https://searchcode.com/codesearch/view/574564/

**Comment by torfsen** [comment]
There is no built-in functionality for communication with the daemon, so you need to implement that yourself. Sockets are a typical approach, but you can also use named pipes or other methods of interprocess communication (IPC).
