### ISSUE TITLE
lockfile is deprecated. any plan to replace it other lock libraries like fasteners?

### ISSUE THREAD

**Issue by sriharshav** [torfsen/service#5]
Thanks for this useful package.

[lockfile](https://pypi.python.org/pypi/lockfile/0.12.2) is deprecated.

Any plan to replace it with recommended package like [fasterners](https://pypi.python.org/pypi/fasteners)

**Comment by torfsen** [comment]
Thanks for the information, @sriharshav!

A deprecated dependency should definitely be replaced, PRs are very welcome.

**Comment by torfsen** [comment]
Fixed by replacing the `lockfile` dependency with [`pid`](https://github.com/trbs/pid/). Note that we still depend on `lockfile` via `python-daemon`, but we don't actually use it any more.

**Comment by torfsen** [comment]
Released in version 0.5.0.
